package com.techshard.graphql.dao.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Vehicle")
public class Vehicle{

	    private String id;

	    private String type;

	    private String modelCode;

	    private String brandName;

	    private String launchDate;
	    
	    @DynamoDBHashKey
		@DynamoDBAutoGeneratedKey

		public String getId() {
			return id;
		}

		public void setId(String id) {
			this.id = id;
		}

		@DynamoDBAttribute
		public String getType() {
			return type;
		}
		     
		public void setType(String type) {
			this.type = type;
		}

		@DynamoDBAttribute
		public String getModelCode() {
			return modelCode;
		}

		public void setModelCode(String modelCode) {
			this.modelCode = modelCode;
		}
		
		@DynamoDBAttribute
		public String getBrandName() {
			return brandName;
		}

		public void setBrandName(String brandName) {
			this.brandName = brandName;
		}
		
		
		@DynamoDBAttribute
		public String getLaunchDate() {
			return launchDate;
		}

		public void setLaunchDate(String launchDate) {
			this.launchDate = launchDate;
		}
	    

	    // Getter and setter
//	    public String getFormattedDate() {
//	        return getLaunchDate().toString();
//	    }
}
